export const ADD_FILE_FOLDER = 'ADDADD_FILE_FOLDER_FILE';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SHOW_HIDE_ADD_MODAL = 'SHOW_HIDE_ADD_MODAL';
export const DELETE_FILE_FOLDER = 'DELETE_FOLDER';
export const UPDATE_CURRENT_FOLDER = 'UPDATE_CURRENT_FOLDER';
export const SET_RIGHT_CLICK_DATA = 'SET_RIGHT_CLICK_DATA';
export const HIDE_CONTEXT_MENU = 'HIDE_CONTEXT_MENU';